### REGISTER
POST localhost:8080/auth/register
Content-Type: application/json

{
    "name": "silvio",
    "surname": "santos",
    "email": "silvio_santos@gmail.com",
    "password": "12345678",
    "document": "09867854311"
}

### LOGIN
POST localhost:8080/auth/login
Content-Type: application/json

{
    "email": "silvio_santos@gmail.com",
    "password": "12345678"
}
