version: "3.8"

services:
  db:
    container_name: ${DB_NAME}
    image: postgre
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - apigo:/var/lib/postgresql/data
