version: "3.9"

services:
    postgres:
        container_name: ${DB_NAME}
        image: postgres:latest
        environment:
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            PG_DATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        volumes:
            - kn:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: unless-stopped
        depends_on:
            - postgres
        ports:
            - "8081:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: password
        volumes:
            - pgadmin:/var/lib/pgadmin
volumes:
    kn:
    pgadmin:
