version: "3.9"

services:
    postgres:
        container_name: ${DB_NAME}
        image: postgres:latest
        environment:
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - kn:/var/lib/postgresql/data
volumes:
    kn:
