### Update Password
PUT http://localhost:8080/user/6fd5d1af-5ecb-4b61-b21e-1310f56e978c
Content-Type: application/json

{
    "password": "123456",
    "previous_password": "agora_essa_nova_senha"
}

### Update User
PATCH http://localhost:8080/user/6fd5d1af-5ecb-4b61-b21e-1310f56e978c
Content-Type: application/json

{
    "name": "claudionir ferreira"
}

### Creating User
POST http://localhost:8080/user
Content-Type: application/json

{
    "name": "claudionir pedro bernardino",
    "username": "clau_pedro",
    "email": "pia_ber@hotmail.com",
    "personal_id": "09876799091",
    "password": "12345678"
}

### Get User By ID
GET http://localhost:8080/user/378e5c58-89f0-457f-8a8c-9e2e1d07453c
Accept: application/json

### Get Many Users
GET http://localhost:8080/users
Content-Type: application/json

### Delete User
DELETE http://localhost:8080/user/66e91f16-5fe1-4334-b823-4b8153ae0af6
Content-Type: application/json

