### Update Password
PUT http://localhost:8080/user/5a98c11e-0290-4dfd-88c1-8e95c17190cd
Content-Type: application/json

{
    "password": "2468101",
    "previous_password": "246810"
}

### Update User
PATCH http://localhost:8080/user/5a98c11e-0290-4dfd-88c1-8e95c17190cd
Content-Type: application/json

{
    "name": "rafael bernardino",
    "username": "username_test",
    "email": "test@gmail.com",
    "personal_id": "10987856789"
}

### Creating User
POST http://localhost:8080/user
Content-Type: application/json

{
    "name": "maristela florentina",
    "username": "maristela_f",
    "email": "maristela@hotmail.com",
    "personal_id": "10878909888",
    "password": "12345678"
}

### Get User By ID
GET http://localhost:8080/user/5a98c11e-0290-4dfd-88c1-8e95c17190cd
Accept: application/json

### Get Many Users
GET http://localhost:8080/users
Content-Type: application/json

### Delete User
DELETE http://localhost:8080/user/66e91f16-5fe1-4334-b823-4b8153ae0af6
Content-Type: application/json

