name: Unit Tests

on: [push]

jobs:
    test:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code in the Go Module
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: "go.mod"

            - name: Run tests
              run: go test ./internal/...
